import type { SeoPageData } from "../types";

const D = "2026-09-26";

export const COMMERCIAL_PAGES: SeoPageData[] = [
  // ── Prix IPTV ──────────────────────────────────────────────────
  {
    slug: "/prix-iptv",
    group: "commercial",
    navLabel: "Prix IPTV",
    cardText: "Combien coûte un abonnement IPTV en 2026 ?",
    title: "Prix IPTV 2026 : combien coûte un abonnement IPTV ?",
    description: "Prix d'un abonnement IPTV en 2026 : tarifs 1, 3, 6 et 12 mois, coût par écran, prix des lecteurs payants et pièges à éviter. Dès 9 € le mois, essai gratuit 24h.",
    keywords: ["prix iptv", "iptv prix", "iptv pas cher", "abonnement iptv pas cher", "iptv 1 mois", "iptv 12 mois", "abonnement iptv 12 mois smart tv", "iptv 12 mois - cdiscount", "iptv meilleur rapport qualité prix", "iptv promo", "buy iptv", "iptv abonne", "tivimate premium prix", "ibo player prix"],
    badge: "Tarifs · Prix IPTV",
    h1: "Prix IPTV 2026 : combien coûte vraiment un abonnement ?",
    intro: "Le **prix d'un abonnement IPTV** en France va d'environ 4 à 15 € par mois selon la durée choisie et le nombre d'écrans. Chez Stream Bleu, il coûte **9 € pour 1 mois**, **29 € pour 3 mois**, **39 € pour 6 mois** et **49 € pour 12 mois**, soit environ 4 € par mois sur un an. À ce prix s'ajoute parfois celui du lecteur (certaines applications Smart TV sont payantes) et, si besoin, d'un boîtier.",
    tldr: [
      "Stream Bleu : 9 € / 1 mois, 29 € / 3 mois, 39 € / 6 mois, 49 € / 12 mois (1 écran).",
      "Plus la durée est longue, plus le prix mensuel baisse : 12 mois ≈ 4,08 €/mois.",
      "Testez 24h gratuitement avant de payer, et fuyez les offres « à vie ».",
    ],
    image: { src: "/abonnement-iptv-france-3.webp", alt: "Comparatif des prix d'abonnement IPTV en France" },
    sections: [
      {
        id: "grille",
        h2: "Grille des prix IPTV Stream Bleu",
        blocks: [
          {
            type: "table",
            head: ["Durée", "1 écran", "Prix par mois", "2 écrans", "3 écrans"],
            rows: [
              ["[1 mois](/tarifs/1-mois)", "9 €", "9,00 €", "18 €", "27 €"],
              ["[3 mois](/tarifs/3-mois)", "29 €", "9,67 €", "50 €", "75 €"],
              ["[6 mois](/tarifs/6-mois)", "39 €", "6,50 €", "69 €", "105 €"],
              ["[12 mois](/tarifs/12-mois)", "49 €", "4,08 €", "89 €", "135 €"],
            ],
            caption: "Tarifs TTC en vigueur ; jusqu'à 10 écrans disponibles sur la page Tarifs.",
          },
          { type: "p", text: "Tous les forfaits donnent accès au même catalogue et aux mêmes fonctions ; seuls la durée et le nombre d'écrans simultanés changent. Détail et commande sur la page [tarifs](/tarifs)." },
        ],
      },
      {
        id: "cout-total",
        h2: "Le coût total : abonnement, lecteur et boîtier",
        blocks: [
          {
            type: "table",
            head: ["Poste", "Coût", "Obligatoire ?"],
            rows: [
              ["Abonnement IPTV", "4 à 9 €/mois selon durée", "Oui"],
              ["Lecteur gratuit (IPTV Smarters, SS IPTV, VLC)", "0 €", "Non"],
              ["Lecteur payant ([IBO Player](/ibo-player), [Smart IPTV](/smart-iptv), [TiviMate Premium](/tivimate))", "Quelques euros par an ou une fois", "Selon votre TV"],
              ["Clé HDMI / [boîtier IPTV](/boitier-iptv)", "30 à 170 €", "Seulement si la TV n'est pas compatible"],
            ],
          },
          { type: "callout", title: "💡 Bon à savoir", text: "Avec le forfait 12 mois, l'activation IBO Player est offerte : pas de coût de lecteur à prévoir sur Samsung ou LG." },
        ],
      },
      {
        id: "pas-cher",
        h2: "IPTV pas cher : où est la limite ?",
        blocks: [
          { type: "p", text: "Un prix bas n'est pas un problème en soi, mais certains signaux doivent alerter : offres « à vie », paiement uniquement en cryptomonnaie ou carte cadeau, absence d'essai ou de contact identifiable. Notre article [IPTV à vie](/blog/iptv-a-vie) explique pourquoi ces offres finissent mal, et [IPTV pas cher](/blog/iptv-pas-cher-france) comment trouver un bon prix sans mauvaise surprise." },
          { type: "p", text: "Les « IPTV 12 mois » vendus sur des marketplaces généralistes sont souvent des codes revendus sans support : en cas de panne, personne ne répond. Préférez un fournisseur qui propose un essai, un support et une [politique de remboursement](/politique-remboursement) claire." },
        ],
      },
      {
        id: "choisir",
        h2: "Quelle durée choisir ?",
        blocks: [
          {
            type: "cards",
            items: [
              { title: "Essai gratuit 24h", text: "Pour vérifier la compatibilité avec votre TV et votre connexion.", href: "/essai-gratuit" },
              { title: "1 mois – 9 €", text: "Pour un événement ou tester en conditions réelles.", href: "/tarifs/1-mois" },
              { title: "12 mois – 49 €", text: "Le meilleur prix mensuel, lecteur IBO offert.", href: "/tarifs/12-mois" },
            ],
          },
        ],
      },
    ],
    faq: [
      { q: "Combien coûte un abonnement IPTV en France ?", a: "Entre 4 et 15 € par mois en moyenne selon la durée et le nombre d'écrans. Chez Stream Bleu : 9 € pour 1 mois, 29 € pour 3 mois, 39 € pour 6 mois et 49 € pour 12 mois." },
      { q: "Quel est l'abonnement IPTV le moins cher par mois ?", a: "Le forfait 12 mois, à 49 €, soit environ 4,08 € par mois pour un écran." },
      { q: "Le prix inclut-il l'application IPTV ?", a: "L'abonnement donne accès aux chaînes. Les lecteurs gratuits (IPTV Smarters, SS IPTV) ne coûtent rien ; certains lecteurs Smart TV sont payants, mais l'activation IBO Player est offerte avec le forfait 12 mois." },
      { q: "Combien coûte un écran supplémentaire ?", a: "Par exemple, le forfait 12 mois passe de 49 € (1 écran) à 89 € (2 écrans) et 135 € (3 écrans). Tous les tarifs jusqu'à 10 écrans sont sur la page Tarifs." },
      { q: "Peut-on être remboursé ?", a: "Les conditions sont détaillées dans notre politique de remboursement. Le plus simple reste de tester 24h gratuitement avant de commander." },
    ],
    related: ["/tarifs", "/abonnement-iptv", "/comparatif-iptv", "/blog/iptv-pas-cher-france", "/blog/iptv-a-vie", "/essai-gratuit", "/iptv-premium"],
    cta: { title: "Abonnement IPTV dès 9 € — testez gratuitement 24h", text: "Sans engagement · Activation rapide · Support en français 7j/7" },
    schema: "WebPage",
    datePublished: D,
    dateModified: D,
  },

  // ── Comparatif IPTV ────────────────────────────────────────────
  {
    slug: "/comparatif-iptv",
    group: "commercial",
    navLabel: "Comparatif IPTV",
    cardText: "Comment comparer et choisir un fournisseur IPTV fiable.",
    title: "Comparatif IPTV 2026 : choisir un fournisseur fiable",
    description: "Comparatif IPTV 2026 : les 8 critères pour choisir un fournisseur IPTV fiable (stabilité, essai, support, appareils, paiement) et les signaux d'alerte.",
    keywords: ["comparatif iptv", "fournisseur iptv", "provider iptv", "service iptv", "iptv fiable", "agence iptv", "agences iptv", "iptv avis", "avis iptv", "trustpilot iptv", "iptv trustpilot", "top iptv", "iptv best", "les meilleurs iptv", "meilleur service iptv", "meilleur site iptv", "iptv meilleur", "iptv stable", "iptv sans coupure", "atlas iptv", "atlas pro iptv", "atlaspro", "iptv atlas", "iptv atlas pro", "atlas iptv pro", "atlaspro in", "atlas pro ontv iphone", "atlas pro ontv sur tv samsung", "atlas pro ott", "king365", "king365 tv", "king365tv", "kingiptv", "king365 iptv", "king365tv box v3", "kingtv365", "ironiptv", "iron iptv", "hotiptv", "hot iptv", "pure iptv", "pureiptv", "pure iptv légal", "iptv pure", "mega iptv", "mega ip tv", "megaott", "mega ott", "mega ott iptv", "megaiptv", "megaott iptv", "megaott net", "royal iptv", "royaliptv", "royale iptv", "dragon iptv", "dragoniptv", "iptv dragon", "eloniptv", "elon iptv", "euro iptv", "euroiptv", "fox iptv", "foxiptv", "iptv fox", "golden iptv", "goldiptv", "neo iptv", "neo tv pro", "neo tv pro 2", "neotv pro", "neotv pro 2", "neox2 iptv", "neox iptv", "purple iptv", "iptv purple", "sharkiptv", "iptv shark", "wise iptv", "wise iptv player", "panda iptv", "pandar iptv", "pandar tv", "xiplayer iptv", "xplayer iptv", "xiptv", "iptv x", "x iptv", "one player iptv", "one tv iptv", "iptv one", "max iptv", "max ott iptv", "iptv max", "magnum iptv", "magnum ott", "ott plus player", "ott plus v2", "ott+ player", "ott pro box", "ottclub player", "worldwide iptv", "vision iptv", "watched iptv", "vipiptv", "top1iptv", "subtv iptv", "strong iptv", "smart4iptv", "saphir iptv", "rg iptv", "room iptv", "premier iptv", "orca iptv", "mario iptv", "majestic iptv", "cod iptv", "9xtream iptv", "avatar iptv", "delta iptv", "dream tv iptv", "eagle iptv", "elite iptv", "fastiptv", "maestro iptv", "lux iptv", "magic iptv", "majax31 iptv", "mitvpro", "moonplayer iptv", "mu3 iptv", "iptv mu3", "nano iptv", "nanomid", "nettv iptv", "niptv", "nord iptv", "obs iptv", "perfectiptv", "phoenix iptv", "platinum iptv", "playiptv", "player iptv solutions", "prestige iptv", "primeiptv", "pro iptv", "qhdtvpro", "quzu iptv", "simpleiptv", "sniper iptv", "sonic iptv", "super iptv", "super tv iptv", "teli iptv", "terra iptv", "tiger iptv", "tv team iptv", "wolf iptv", "xtreamtv", "yootix tv", "yu2go", "ottiptv", "iptv+", "iptv24", "iptv365", "iptv4on", "iptv4u", "iptvfull", "iptvgold", "iptvisuel", "iptvone", "iptvplus", "iptvstore", "iptv az", "iptv 365", "iptv com", "iptv connect", "iptv connect pro", "iptv global", "iptv streaming", "iptv total", "iptv life", "iptv tech", "iptv high tech", "iptv mondial", "iptv set", "iptv run", "iptv flex", "iptv motion", "iptv xyz", "iptv hunt", "iptv monster", "iptv pro2", "iptv revolution", "iptv secured", "iptv wings"],
    badge: "Comparatif · 2026",
    h1: "Comparatif IPTV 2026 : comment choisir un fournisseur fiable",
    intro: "Pour comparer des **fournisseurs IPTV**, le nombre de chaînes annoncé compte peu. Ce qui fait la différence au quotidien : la **stabilité aux heures de pointe**, la possibilité de **tester gratuitement**, un **support joignable en français**, la compatibilité avec vos appareils et des conditions de paiement et de remboursement claires. Voici notre grille de comparaison en 8 critères, applicable à n'importe quel service IPTV.",
    tldr: [
      "Testez toujours pendant un match ou un soir de semaine : c'est là que les serveurs faibles décrochent.",
      "Un fournisseur sérieux propose un essai, un support identifiable et une politique de remboursement.",
      "Fuyez les offres « à vie », les prix irréalistes et les paiements sans protection.",
    ],
    sections: [
      {
        id: "criteres",
        h2: "Les 8 critères pour comparer les services IPTV",
        blocks: [
          {
            type: "table",
            head: ["Critère", "Ce qu'il faut vérifier", "Stream Bleu"],
            rows: [
              ["Stabilité", "Pas de coupure en soirée ou pendant un grand match", "Serveurs optimisés pour la France ([IPTV stable](/blog/iptv-stable-france))"],
              ["Essai", "Test gratuit sans carte bancaire", "[Essai 24h](/essai-gratuit)"],
              ["Support", "Contact en français, réponse rapide", "WhatsApp et e-mail, 7j/7"],
              ["Appareils", "Smart TV, Fire TV, mobile, PC, MAG", "Tous ([appareils](/appareils-iptv))"],
              ["Connexions", "Choix du nombre d'écrans", "1 à 10 écrans"],
              ["Formats", "Xtream Codes, M3U, portail MAG", "Les trois"],
              ["Prix", "Tarifs affichés, sans frais cachés", "Dès 9 € ([prix IPTV](/prix-iptv))"],
              ["Conditions", "CGU, remboursement, mentions claires", "[Remboursement](/politique-remboursement)"],
            ],
          },
        ],
      },
      {
        id: "methode",
        h2: "Notre méthode de test",
        blocks: [
          {
            type: "ol",
            items: [
              "Installer le service sur trois appareils : Fire TV Stick, Smart TV Samsung ou LG, smartphone.",
              "Mesurer le temps de zapping et la stabilité un soir de semaine entre 20h et 23h.",
              "Contacter le support avec une question technique et chronométrer la réponse.",
              "Lire les conditions : remboursement, résiliation, protection des données.",
            ],
          },
          { type: "p", text: "Ces étapes prennent une soirée et vous évitent la plupart des mauvaises surprises. Pour notre propre classement, voir [meilleur IPTV France](/meilleur-iptv-france) et les [avis clients](/avis)." },
        ],
      },
      {
        id: "alerte",
        h2: "Les signaux d'alerte",
        blocks: [
          {
            type: "ul",
            items: [
              "**Offres « à vie »** : modèle économique impossible, voir [IPTV à vie](/blog/iptv-a-vie).",
              "**Aucun essai possible** : vous achetez à l'aveugle.",
              "**Paiement uniquement en crypto ou carte cadeau** : aucune protection en cas de litige.",
              "**Avis uniquement sur le site du vendeur** : croisez avec des plateformes indépendantes comme Trustpilot ou Google.",
              "**Promesses irréalistes** : « 0 coupure garantie à vie », « toutes les chaînes du monde »…",
            ],
          },
        ],
      },
      {
        id: "noms",
        h2: "Et les services que l'on voit passer (Atlas Pro, King365, etc.) ?",
        blocks: [
          { type: "p", text: "Des dizaines de noms de services et de panels IPTV circulent en France et en Europe francophone — certains ci-dessous, en vrac, simplement pour vous aider si c'est l'un d'eux qui vous a amené sur cette page. **Nous ne les avons pas testés, ne sommes affiliés à aucun d'eux, ne les recommandons pas et ne publions aucun avis à leur sujet** (positif ou négatif). La grille de critères ci-dessus s'applique à n'importe lequel d'entre eux : demandez un essai, testez aux heures de pointe, vérifiez le support et lisez les conditions avant de payer." },
          { type: "chips", items: ["Atlas Pro", "King365", "Iron IPTV", "Hot IPTV", "Pure IPTV", "Mega IPTV / MegaOTT", "Royal / Royale IPTV", "Dragon IPTV", "Elon IPTV", "Euro IPTV", "Fox IPTV", "Golden IPTV", "Neo IPTV / Neo TV Pro", "Purple IPTV", "Shark IPTV", "Wise IPTV", "Panda / Pandar IPTV", "X IPTV / Xiptv / Xplayer", "One IPTV / One Player", "Max IPTV", "Magnum IPTV", "OTT Plus / OTT Pro", "Worldwide IPTV", "Vision IPTV", "Watched IPTV", "VIP IPTV", "Top1 IPTV", "Subtv IPTV", "Strong IPTV", "Smart4IPTV", "Saphir IPTV", "RG IPTV", "Room IPTV", "Premier IPTV", "Orca IPTV", "Mario IPTV", "Majestic IPTV", "Cod IPTV", "9xtream IPTV", "Avatar IPTV", "Delta IPTV", "Dream TV IPTV", "Eagle IPTV", "Elite IPTV", "Fastiptv", "Maestro IPTV", "Lux IPTV", "Magic IPTV", "Majax31 IPTV", "Mitvpro", "Moonplayer IPTV", "Mu3 IPTV", "Nano IPTV / Nanomid", "Nettv IPTV", "Niptv", "Nord IPTV", "Obs IPTV", "Perfectiptv", "Phoenix IPTV", "Platinum IPTV", "Playiptv", "Player IPTV Solutions", "Prestige IPTV", "Primeiptv", "Pro IPTV", "QHDTVPro", "Quzu IPTV", "Simpleiptv", "Sniper IPTV", "Sonic IPTV", "Super IPTV", "Teli IPTV", "Terra IPTV", "Tiger IPTV", "TV Team IPTV", "Wolf IPTV", "Xtreamtv", "Yootix TV", "Yu2go", "Ottiptv", "IPTV+", "IPTV24", "IPTV365", "IPTV4on", "IPTV4u", "IPTVfull", "IPTVgold", "IPTVisuel", "IPTVone", "IPTVplus", "IPTVstore", "IPTV Az", "IPTV 365", "IPTV Com", "IPTV Connect", "IPTV Connect Pro", "IPTV Global", "IPTV Streaming", "IPTV Total", "IPTV Life", "IPTV Tech", "IPTV High Tech", "IPTV Mondial", "IPTV Set", "IPTV Run", "IPTV Flex", "IPTV Motion", "IPTV Xyz", "IPTV Hunt", "IPTV Monster", "IPTV Pro2", "IPTV Revolution", "IPTV Secured", "IPTV Wings"] },
          { type: "p", text: "Certaines recherches comme « iptv az » ou « iptv 365 » décrivent une offre plutôt qu'une marque précise (« de A à Z », « toute l'année ») : elles ne désignent aucun service en particulier." },
          { type: "p", text: "Ne confondez pas non plus les **services** (qui fournissent les chaînes) et les **applications** (qui les lisent) : IPTV Smarters, TiviMate, Flix IPTV ou IBO Player sont des lecteurs, pas des fournisseurs — voir notre [comparatif des applications IPTV](/applications-iptv). Et une application au nom proche d'un service ne veut pas dire qu'ils sont liés : par exemple, [IPTV Smarters Pro](/iptv-smarters-pro) et [Smart IPTV](/smart-iptv) sont deux applications distinctes, malgré la ressemblance de leurs noms." },
        ],
      },
      {
        id: "legalite",
        h2: "La question de la légalité",
        blocks: [
          { type: "p", text: "La technologie IPTV est légale ; la légalité d'un service dépend des droits de diffusion qu'il détient pour les contenus proposés. L'[Arcom](https://www.arcom.fr) peut faire bloquer les services qui diffusent sans droits. Notre analyse complète : [l'IPTV est-il légal en France ?](/blog/iptv-legal-france) et notre page [avertissement](/avertissement)." },
        ],
      },
    ],
    faq: [
      { q: "Comment choisir un fournisseur IPTV fiable ?", a: "Vérifiez la stabilité aux heures de pointe pendant un essai gratuit, la réactivité du support en français, la compatibilité avec vos appareils, et la clarté des conditions de paiement et de remboursement." },
      { q: "Quel est le meilleur service IPTV en France ?", a: "Le meilleur service est celui qui reste stable chez vous, aux heures où vous regardez. Testez plusieurs offres avec un essai gratuit et appliquez notre grille en 8 critères. Notre sélection est détaillée sur la page Meilleur IPTV France." },
      { q: "Les avis Trustpilot sur l'IPTV sont-ils fiables ?", a: "Ils sont utiles s'ils sont nombreux, récents et détaillés. Croisez plusieurs sources (Trustpilot, Google, forums) et méfiez-vous des avis tous publiés le même jour." },
      { q: "IPTV Smarters ou TiviMate sont-ils des fournisseurs IPTV ?", a: "Non, ce sont des applications de lecture. Elles ne fournissent aucune chaîne : il faut un abonnement auprès d'un fournisseur IPTV." },
      { q: "Qu'est-ce qu'une « agence IPTV » ?", a: "Le terme désigne généralement un revendeur d'abonnements IPTV. Appliquez les mêmes critères qu'à un fournisseur : essai, support identifiable, conditions claires." },
      { q: "Atlas Pro est-il un bon service IPTV ?", a: "Nous ne connaissons pas Atlas Pro (ou Atlas Pro OnTv) de l'intérieur, n'y sommes pas affiliés et ne pouvons donc pas le recommander ni le déconseiller. Comme pour tout service, appliquez notre grille en 8 critères — essai gratuit, stabilité testée aux heures de pointe, support joignable, conditions de remboursement claires — avant de payer." },
      { q: "King365 (TV) est-il fiable ?", a: "Nous ne sommes pas affiliés à King365 et n'avons publié aucun test le concernant. Demandez systématiquement un essai avant de payer, et vérifiez la stabilité un soir de match plutôt que de vous fier uniquement aux avis affichés sur le site du vendeur." },
    ],
    related: ["/meilleur-iptv-france", "/prix-iptv", "/avis", "/blog/iptv-france-avis", "/blog/iptv-stable-france", "/blog/iptv-a-vie", "/applications-iptv", "/essai-gratuit"],
    cta: { title: "Comparez par vous-même : 24h d'essai gratuit", text: "Testez Stream Bleu aux heures de pointe, sur vos appareils, sans engagement." },
    itemList: [
      { name: "Atlas Pro" },
      { name: "King365" },
      { name: "Iron IPTV" },
      { name: "Hot IPTV" },
      { name: "Pure IPTV" },
      { name: "Mega IPTV / MegaOTT" },
      { name: "Royal / Royale IPTV" },
      { name: "Dragon IPTV" },
      { name: "Elon IPTV" },
      { name: "Euro IPTV" },
      { name: "Fox IPTV" },
      { name: "Golden IPTV" },
      { name: "Neo IPTV / Neo TV Pro" },
      { name: "Purple IPTV" },
      { name: "Shark IPTV" },
      { name: "Wise IPTV" },
      { name: "Panda / Pandar IPTV" },
      { name: "X IPTV / Xiptv / Xplayer" },
      { name: "One IPTV / One Player" },
      { name: "Max IPTV" },
      { name: "Magnum IPTV" },
      { name: "OTT Plus / OTT Pro" },
      { name: "Worldwide IPTV" },
      { name: "Vision IPTV" },
      { name: "Watched IPTV" },
      { name: "VIP IPTV" },
      { name: "Top1 IPTV" },
      { name: "Subtv IPTV" },
      { name: "Strong IPTV" },
      { name: "Smart4IPTV" },
      { name: "Saphir IPTV" },
      { name: "RG IPTV" },
      { name: "Room IPTV" },
      { name: "Premier IPTV" },
      { name: "Orca IPTV" },
      { name: "Mario IPTV" },
      { name: "Majestic IPTV" },
      { name: "Cod IPTV" },
      { name: "9xtream IPTV" },
      { name: "Avatar IPTV" },
      { name: "Delta IPTV" },
      { name: "Dream TV IPTV" },
      { name: "Eagle IPTV" },
      { name: "Elite IPTV" },
      { name: "Fastiptv" },
      { name: "Maestro IPTV" },
      { name: "Lux IPTV" },
      { name: "Magic IPTV" },
      { name: "Majax31 IPTV" },
      { name: "Mitvpro" },
      { name: "Moonplayer IPTV" },
      { name: "Mu3 IPTV" },
      { name: "Nano IPTV / Nanomid" },
      { name: "Nettv IPTV" },
      { name: "Niptv" },
      { name: "Nord IPTV" },
      { name: "Obs IPTV" },
      { name: "Perfectiptv" },
      { name: "Phoenix IPTV" },
      { name: "Platinum IPTV" },
      { name: "Playiptv" },
      { name: "Player IPTV Solutions" },
      { name: "Prestige IPTV" },
      { name: "Primeiptv" },
      { name: "Pro IPTV" },
      { name: "QHDTVPro" },
      { name: "Quzu IPTV" },
      { name: "Simpleiptv" },
      { name: "Sniper IPTV" },
      { name: "Sonic IPTV" },
      { name: "Super IPTV" },
      { name: "Teli IPTV" },
      { name: "Terra IPTV" },
      { name: "Tiger IPTV" },
      { name: "TV Team IPTV" },
      { name: "Wolf IPTV" },
      { name: "Xtreamtv" },
      { name: "Yootix TV" },
      { name: "Yu2go" },
      { name: "Ottiptv" },
      { name: "IPTV+" },
      { name: "IPTV24" },
      { name: "IPTV365" },
      { name: "IPTV4on" },
      { name: "IPTV4u" },
      { name: "IPTVfull" },
      { name: "IPTVgold" },
      { name: "IPTVisuel" },
      { name: "IPTVone" },
      { name: "IPTVplus" },
      { name: "IPTVstore" },
      { name: "IPTV Az" },
      { name: "IPTV 365" },
      { name: "IPTV Com" },
      { name: "IPTV Connect" },
      { name: "IPTV Connect Pro" },
      { name: "IPTV Global" },
      { name: "IPTV Streaming" },
      { name: "IPTV Total" },
      { name: "IPTV Life" },
      { name: "IPTV Tech" },
      { name: "IPTV High Tech" },
      { name: "IPTV Mondial" },
      { name: "IPTV Set" },
      { name: "IPTV Run" },
      { name: "IPTV Flex" },
      { name: "IPTV Motion" },
      { name: "IPTV Xyz" },
      { name: "IPTV Hunt" },
      { name: "IPTV Monster" },
      { name: "IPTV Pro2" },
      { name: "IPTV Revolution" },
      { name: "IPTV Secured" },
      { name: "IPTV Wings" }
    ],
    schema: "WebPage",
    datePublished: D,
    dateModified: D,
  },
];
