import { notFound } from "next/navigation";
import type { Metadata } from "next";
import PlanOrderForm from "../pricing/PlanOrderForm";
import PlanFAQ, { type FaqItem } from "../pricing/PlanFAQ";

interface PlanPageData {
  title: string;
    description: string;
      keywords: string;
        canonical: string;
          badge: string;
            heading: string;
              price: string;
                faqItems: FaqItem[];
                }

                const planData: Record<string, PlanPageData> = {
                  "1-month": {
                      title: "1 Month IPTV Plan — $15 | Stream Bleu",
                          description: "Get 1 month of IPTV en France for $15. 25 000+ live channels, 4K quality, Ligue 1, beIN Sports, CTV and more. No contract. Login credentials sent within minutes.",
                              keywords: "Stream Bleu 1 month, IPTV monthly plan France, IPTV $15 France, month to month Stream Bleu",
                                  canonical: "https://streambleu.fr/1-month",
                                      badge: "IPTV CANADA · 1 MONTH PLAN",
                                          heading: "1 Month Plan — $15",
                                              price: "15",
                                                  faqItems: [
                                                        { q: "What is included in the 1-month IPTV plan?", a: "The 1-month plan gives you full access to 25 000+ live TV channels, 120 000+ movies & series in 4K, including Ligue 1, beIN Sports, RMC Sport, CTV, and more — all for $15." },
                                                              { q: "How do I receive my login credentials after ordering?", a: "After submitting your order form, our team will send your IPTV login credentials directly to your email within minutes." },
                                                                    { q: "Which devices are compatible with this IPTV service?", a: "Our IPTV service works on Smart TVs, Firestick, Android TV, Apple TV, phones, tablets, MAG boxes, and more." },
                                                                          { q: "Is there a contract or commitment required?", a: "No contracts at all. The 1-month plan is completely flexible — cancel anytime, no questions asked." },
                                                                                { q: "Can I upgrade to a longer plan later?", a: "Yes! You can upgrade to our 3-month, 6-month, or 12-month plan at any time to save more per month." },
                                                                                      { q: "What payment methods do you accept?", a: "We accept e-Transfer, credit/debit cards, and other payment methods. Contact us on WhatsApp for details." },
                                                                                            { q: "Is there a essai gratuit available?", a: "Yes, we offer a 24h essai gratuit. Visit our Essai Gratuit page to get started before committing." },
                                                                                                  { q: "What if I have issues with my IPTV service?", a: "We offer 24/7 Français support via WhatsApp and email to help you resolve any issues quickly." },
                                                                                                      ],
                                                                                                        },
                                                                                                          "3-months": {
                                                                                                              title: "3 Month IPTV Plan — 29€ | Stream Bleu",
                                                                                                                  description: "Get 3 months of IPTV en France for 29€. 25 000+ live channels, 4K quality, Ligue 1, beIN Sports, CTV and more. No contract. Login credentials sent within minutes.",
                                                                                                                      keywords: "Stream Bleu 3 months, IPTV quarterly plan France, IPTV 29€ France, 3 month Stream Bleu",
                                                                                                                          canonical: "https://streambleu.fr/3-months",
                                                                                                                              badge: "IPTV CANADA · 3 MONTH PLAN",
                                                                                                                                  heading: "3 Month Plan — 29€",
                                                                                                                                      price: "29",
                                                                                                                                          faqItems: [
                                                                                                                                                { q: "What is included in the 3-month IPTV plan?", a: "The 3-month plan gives you full access to 25 000+ live TV channels, 120 000+ movies & series in 4K, including Ligue 1, beIN Sports, RMC Sport, CTV, and more — all for 29€." },
                                                                                                                                                      { q: "How do I receive my login credentials after ordering?", a: "After submitting your order form, our team will send your IPTV login credentials directly to your email within minutes." },
                                                                                                                                                            { q: "Which devices are compatible with this IPTV service?", a: "Our IPTV service works on Smart TVs, Firestick, Android TV, Apple TV, phones, tablets, MAG boxes, and more." },
                                                                                                                                                                  { q: "Is there a contract or commitment required?", a: "No contracts at all. The 3-month plan is completely flexible — cancel anytime, no questions asked." },
                                                                                                                                                                        { q: "How much do I save compared to the 1-month plan?", a: "With the 3-month plan at 29€, you pay under $10/month instead of $15 — saving you over 33%." },
                                                                                                                                                                              { q: "What payment methods do you accept?", a: "We accept e-Transfer, credit/debit cards, and other payment methods. Contact us on WhatsApp for details." },
                                                                                                                                                                                    { q: "Is there a essai gratuit available?", a: "Yes, we offer a 24h essai gratuit. Visit our Essai Gratuit page to get started before committing." },
                                                                                                                                                                                          { q: "What if I have issues with my IPTV service?", a: "We offer 24/7 Français support via WhatsApp and email to help you resolve any issues quickly." },
                                                                                                                                                                                              ],
                                                                                                                                                                                                },
                                                                                                                                                                                                  "6-months": {
                                                                                                                                                                                                      title: "6 Month IPTV Plan — 39€ | Stream Bleu",
                                                                                                                                                                                                          description: "Get 6 months of IPTV en France for 39€. 25 000+ live channels, 4K quality, Ligue 1, beIN Sports, CTV and more. No contract. Login credentials sent within minutes.",
                                                                                                                                                                                                              keywords: "Stream Bleu 6 months, IPTV semi-annual plan France, IPTV 39€ France, 6 month Stream Bleu",
                                                                                                                                                                                                                  canonical: "https://streambleu.fr/6-months",
                                                                                                                                                                                                                      badge: "IPTV CANADA · 6 MONTH PLAN",
                                                                                                                                                                                                                          heading: "6 Month Plan — 39€",
                                                                                                                                                                                                                              price: "39",
                                                                                                                                                                                                                                  faqItems: [
                                                                                                                                                                                                                                        { q: "What is included in the 6-month IPTV plan?", a: "The 6-month plan gives you full access to 25 000+ live TV channels, 120 000+ movies & series in 4K, including Ligue 1, beIN Sports, RMC Sport, CTV, and more — all for 39€." },
                                                                                                                                                                                                                                              { q: "How do I receive my login credentials after ordering?", a: "After submitting your order form, our team will send your IPTV login credentials directly to your email within minutes." },
                                                                                                                                                                                                                                                    { q: "Which devices are compatible with this IPTV service?", a: "Our IPTV service works on Smart TVs, Firestick, Android TV, Apple TV, phones, tablets, MAG boxes, and more." },
                                                                                                                                                                                                                                                          { q: "Is there a contract or commitment required?", a: "No contracts at all. The 6-month plan is completely flexible — cancel anytime, no questions asked." },
                                                                                                                                                                                                                                                                { q: "How much do I save compared to the 1-month plan?", a: "With the 6-month plan at 39€, you pay only $6.50/month — saving you over 56% compared to the monthly plan." },
                                                                                                                                                                                                                                                                      { q: "What payment methods do you accept?", a: "We accept e-Transfer, credit/debit cards, and other payment methods. Contact us on WhatsApp for details." },
                                                                                                                                                                                                                                                                            { q: "Is there a essai gratuit available?", a: "Yes, we offer a 24h essai gratuit. Visit our Essai Gratuit page to get started before committing." },
                                                                                                                                                                                                                                                                                  { q: "What if I have issues with my IPTV service?", a: "We offer 24/7 Français support via WhatsApp and email to help you resolve any issues quickly." },
                                                                                                                                                                                                                                                                                      ],
                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                          "12-months": {
                                                                                                                                                                                                                                                                                              title: "12 Month IPTV Plan — 49€ | Stream Bleu",
                                                                                                                                                                                                                                                                                                  description: "Get 12 months of IPTV en France for 49€. 25 000+ live channels, 4K quality, Ligue 1, beIN Sports, CTV and more. No contract. Login credentials sent within minutes.",
                                                                                                                                                                                                                                                                                                      keywords: "Stream Bleu 12 months, IPTV annual plan France, IPTV 49€ France, yearly Stream Bleu",
                                                                                                                                                                                                                                                                                                          canonical: "https://streambleu.fr/12-months",
                                                                                                                                                                                                                                                                                                              badge: "IPTV CANADA · 12 MONTH PLAN",
                                                                                                                                                                                                                                                                                                                  heading: "12 Month Plan — 49€",
                                                                                                                                                                                                                                                                                                                      price: "49",
                                                                                                                                                                                                                                                                                                                          faqItems: [
                                                                                                                                                                                                                                                                                                                                { q: "What is included in the 12-month IPTV plan?", a: "The 12-month plan gives you full access to 25 000+ live TV channels, 120 000+ movies & series in 4K, including Ligue 1, beIN Sports, RMC Sport, CTV, and more — all for 49€." },
                                                                                                                                                                                                                                                                                                                                      { q: "How do I receive my login credentials after ordering?", a: "After submitting your order form, our team will send your IPTV login credentials directly to your email within minutes." },
                                                                                                                                                                                                                                                                                                                                            { q: "Which devices are compatible with this IPTV service?", a: "Our IPTV service works on Smart TVs, Firestick, Android TV, Apple TV, phones, tablets, MAG boxes, and more." },
                                                                                                                                                                                                                                                                                                                                                  { q: "Is there a contract or commitment required?", a: "No contracts at all. The 12-month plan is completely flexible — cancel anytime, no questions asked." },
                                                                                                                                                                                                                                                                                                                                                        { q: "How much do I save compared to the 1-month plan?", a: "With the 12-month plan at 49€, you pay only $4/month — saving you over 73% compared to the monthly plan." },
                                                                                                                                                                                                                                                                                                                                                              { q: "What payment methods do you accept?", a: "We accept e-Transfer, credit/debit cards, and other payment methods. Contact us on WhatsApp for details." },
                                                                                                                                                                                                                                                                                                                                                                    { q: "Is there a essai gratuit available?", a: "Yes, we offer a 24h essai gratuit. Visit our Essai Gratuit page to get started before committing." },
                                                                                                                                                                                                                                                                                                                                                                          { q: "What if I have issues with my IPTV service?", a: "We offer 24/7 Français support via WhatsApp and email to help you resolve any issues quickly." },
                                                                                                                                                                                                                                                                                                                                                                              ],
                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                export function generateStaticParams() {
  return [
    { plan: "1-month" },
    { plan: "3-months" },
    { plan: "6-months" },
    { plan: "12-months" },
  ];
}

export async function generateMetadata({ params }: { params: Promise<{ plan: string }> }): Promise<Metadata> {
                                                                                                                                                                                                                                                                                                                                                                                  const { plan } = await params;
                                                                                                                                                                                                                                                                                                                                                                                    const data = planData[plan];
                                                                                                                                                                                                                                                                                                                                                                                      if (!data) return { title: "Plan Not Found" };
                                                                                                                                                                                                                                                                                                                                                                                        return {
                                                                                                                                                                                                                                                                                                                                                                                            title: data.title,
                                                                                                                                                                                                                                                                                                                                                                                                description: data.description,
                                                                                                                                                                                                                                                                                                                                                                                                    keywords: data.keywords,
                                                                                                                                                                                                                                                                                                                                                                                                        alternates: { canonical: data.canonical },
                                                                                                                                                                                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                          export default async function PlanPage({ params }: { params: Promise<{ plan: string }> }) {
                                                                                                                                                                                                                                                                                                                                                                                                            const { plan } = await params;
                                                                                                                                                                                                                                                                                                                                                                                                              const data = planData[plan];
                                                                                                                                                                                                                                                                                                                                                                                                                if (!data) notFound();

                                                                                                                                                                                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                                                                                                                                                                                      <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <main style={{ background: "linear-gradient(to left, #daf0f2 0%, #fce8e4 100%)", color: "#000000", minHeight: "100vh", fontFamily: "inherit" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                          <div style={{ maxWidth: 780, margin: "0 auto", padding: "48px 20px 80px" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* Badge */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ marginBottom: 24 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span style={{ background: "#F96E5B", color: "#fff", fontSize: 12, fontWeight: 700, padding: "5px 14px", borderRadius: 999, letterSpacing: 1 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {data.badge}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* Heading */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h1 style={{ fontSize: "clamp(2rem,5vw,2.8rem)", fontWeight: 900, marginBottom: 8, lineHeight: 1.15 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {data.heading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ width: 48, height: 4, background: "#F96E5B", borderRadius: 2, marginBottom: 24 }} />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* Subtitle */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p style={{ color: "#000000", fontSize: 15, marginBottom: 36 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Fill out the form below to place your order.<br />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              We&apos;ll send your login credentials to your email within minutes.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Order Form */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ background: "#1A3D45", borderRadius: 24, padding: "32px", boxShadow: "0 8px 32px rgba(26,61,69,0.25)", marginBottom: 32 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <PlanOrderForm plan={plan} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* FAQ */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ background: "#1A3D45", borderRadius: 24, padding: "32px", boxShadow: "0 8px 32px rgba(26,61,69,0.25)" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p style={{ color: "#F96E5B", fontSize: 11, fontWeight: 700, letterSpacing: "0.1em", textTransform: "uppercase", marginBottom: 12 }}>FAQ</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h2 style={{ color: "#ffffff", fontSize: "1.4rem", fontWeight: 800, marginBottom: 24 }}>Frequently Asked Questions</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <PlanFAQ items={data.faqItems} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }